name: flutter_flowin_example
description: A minimal example of building a screen with the Flowin design system.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_flowin:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
