name: flutter_flowin
description: Flowin Design UI flutter package
version: 0.2.0+2
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  figma_squircle: ^0.6.3
  flutter:
    sdk: flutter
  ios_color_picker:
    git:
      url: https://github.com/luisburgos/ios_color_picker
      ref: master
  lucide_icons_flutter: ^3.1.15
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.2.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Supreme
      fonts:
        - asset: assets/fonts/Supreme-Thin.ttf
          weight: 100
        - asset: assets/fonts/Supreme-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Supreme-Extralight.ttf
          weight: 200
        - asset: assets/fonts/Supreme-ExtralightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Supreme-Light.ttf
          weight: 300
        - asset: assets/fonts/Supreme-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Supreme-Regular.ttf
          weight: 400
        - asset: assets/fonts/Supreme-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Supreme-Medium.ttf
          weight: 500
        - asset: assets/fonts/Supreme-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Supreme-Bold.ttf
          weight: 700
        - asset: assets/fonts/Supreme-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Supreme-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/Supreme-ExtraboldItalic.ttf
          weight: 800
          style: italic
